### PR TITLE
Fixes pintman/workadv_das-labor#6 rename map.json to main.json

### PR DESCRIPTION
**Pull request by Mythozz**
For rC3 integration map.json has been renamed to main.json.

### CODE REVIEW

**Comment by pintman** [comment]
I can surely integrate the change. However, https://virtuallab.das-labor.org/ still points to main.json. This has to be changed as well.

**Comment by pintman** [comment]
Added a link from main.json to map.json. I hope this will fix the naming problem and allows both names to be used.

**Comment by fridtjof** [comment]
I fixed the redirect to point to `main.json` now.

**Comment by pintman** [comment]
Thanks for changing the redirect.

**Pull request merged**
